= filabel
:toc:
:note-caption: :information_source:
:warning-caption: :warning:

Tool for labeling PRs at GitHub by globs.


== Zadání úkolu 2

Vaším úkolem za 5 bodů je rozšířit CLI  aplikaci z minulé úlohy o webové rozhraní.
Stávající funkcionalita ale musí být zachována,
mimo původní aplikace půjde tedy navíc spustit web server a to pomocí `flask run`.

Výslednou aplikaci nasaďte na PythonAnywhere, nebo jiný veřejný WSGI hosting.
Odkaz na běžící aplikaci a repozitář nám pošlete e-mailem.

Nasazenou aplikaci nastavte tak,
abychom mohli chování vyzkoušet zasláním Pull Requestu do vašeho repozitáře.

== Specifikace

Aplikace musí přijímat na adrese `/` GitHub webhooky (metoda POST).
Aplikace musí správně zpracovat https://developer.github.com/webhooks/[webhooky]
`pull_request` a `ping` ve formátu JSON.

Na `ping` aplikace správně odpoví dle dokumentace.

Na `pull_request` aplikace také správně odpoví dle dokumentace,
navíc nastaví správně štítky, dle konfiguračního souboru a zadání minulé úlohy.

Aplikace musí podporovat zabezpečení pomocí webhook secret (viz dále).

Na adrese `/` se při požadavku GET bude nacházet jednoduchá HTML stránka,
ze které bude jasné, jaká pravidla platí a jaký uživatel bude štítky nastavovat.
Uživatelské jméno se na stránce zobrazí podle použitého tokenu,
není zadrátované do kódu aplikace nebo šablony.

Musíte využít šablonu.
Nebudeme hodnotit vzhled stránky,
ale využijte HTML pro prezentaci informací.
Vydumpování Python slovníku do `<pre>` boxu není dostačující.
Pokud si nejste jisti, použijte zanořené seznamy (štítek: pravidla).

=== Spouštění aplikace

Aplikace se musí dát spustit pomocí příkazu `flask run`
a to nastavením proměnné prostředí `FLASK_APP` na `filabel.py`.

[source,console]
$ export FLASK_APP=filabel.py
$ flask run

Zároveň je možné pomocí proměnné prostředí nastavit,
kde má aplikace hledat konfigurační soubor(y).

Pomocí proměnné `FILABEL_CONFIG` je možné nastavit cestu k jednomu konfiguračnímu souboru,
nebo více souborům, oddělených dvojtečkou.

V konfiguračních souborech hledáte sekce `github` a `labels`.

CLI aplikace z minulého týdne musí stále fungovat a testy z minula musí procházet.

=== Zabezpečení webhooku

Protože příjímání událostí z internetu může být riskantní,
nabízí GitHub možnost webhooky zabezpečit proti zneužiti.
Abyste rozpoznali, že vám událost poslal právě GitHub,
je ke každému requestu z GitHubu přiložená hlavička `X-Hub-Signature`, např:

[source]
X-Hub-Signature: sha1=0b861d9a594a4f421cabcdef75d5aefc46df8967

která vám říká,
že pokud použijete HMAC hexdigest s odpovídající hash funkcí a s klíčem,
který je uvedený v položce `secret`, na celé tělo requestu
a vámi spočítaný výsledek se shoduje s tím v hlavičce `X-Hub-Signature`,
tak tento request přišel z GitHubu, a můžete mu tedy veřit.

Více informací a příklad v Ruby je na
https://developer.github.com/webhooks/securing/[github securing].

Do konfigurančího souboru (sekce `github`) tedy přidejte položku `secret`.
Při nastavování webhooku na GitHubu použijte stejný secret jako při nasazování aplikace.

== Automatické testy

Testy z minula stále musí procházet.
Existuje i několik nových testů v souboru `test_web_smoke.py`.

Pro spuštění pouze nových testů můžete použít:

[source,console]
$ python -m pytest -v -k web test

Pro nové testy není třeba speciální setup z minula.

WARNING: Testy **netestují hlavní funkcionalitu aplikace**,
ale pouze přidružené věci, jako importovatelnost,
přítomnost usernamu na hlavní stránce,
ping, ověření „secret“.
Ujistěte se, že vaše nasazená aplikace funguje, jak má.

Následuje text z minula, který stále platí:

Pro spuštění testů nainstalujte do virtuálního prostředí balík `pytest`.

Testy vyžadují určitý setup repozitářů. Pro jeho vytvoření použijte skript
`test_environment/setup.sh`. Je třeba nastavit proměnné prostředí
`GH_TOKEN` a `GH_USER`.
Token musí příslušet danému uživateli a mít scope `repo`.

Skript využívá program https://hub.github.com/[hub],
který si *nejprve zprovozněte*.

Testy jsou napsané tak, že pokud váš program funguje dle zadání,
dají se pouštět opakovaně. Pokud ale dle zadání nefunguje,
je třeba smazat všechny štítky.
Alternativně můžete testovací repozitáře smazat pomocí skriptu
`test_environment/delete.sh` (potřeba scope `delete_repo`) a vytvořit znovu.
Vytváření repozitářů a Pull Requestů může trvat jednotky minut.

Pro spuštění testů nastavte stejné proměnné prostředí (`GH_TOKEN` a `GH_USER`).

[source,console]
$ export GH_USER=anicka
$ export GH_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
$ python -m pytest -v test

Testy v souboru test_radioactive_waste.py trvají dlouho a mají potenciál
vyřadit vás na hodinu z přístupu ke GitHub API.
Když ladíte ostatní testy, doporučujeme je vypínat pomocí přepínače `-k`:

[source,console]
$ python -m pytest -v -k "not radioactive" test

Testy předpokládají, že se štítky mění podle běhu předchozích testů.
Nepouštějte tedy jednotlivé testy samostatně.

Testy si můžete zkopírovat k sobě do repozitáře, považujte je za Public Domain.
Nepřidejte ale do repozitáře omylem soubor `auth.real.cfg`,
který se v průběhu testů dočasně vytváří a obsahuje váš token.

NOTE: Testy proti živému API, navíc napsané tak,
že se jednotlivé testy navzájem ovlivňují, jsou ukázkou toho,
jak se to nemá dělat.
Pokud narazíte v testech na problém, nebo nevíte jak dál, zeptejte se.
K tomu, jak se to dělá pořádně, se v předmětu dostaneme později.

WARNING: Testy netestují barevnost výstupu. I neobarvený výstup projde testy.
Barevnost kontrolujte očima.

== Odevzdání úkolu

Odkazy na repozitář a běžící aplikaci nám pošlete e-mailem.
Pro odevzdání v repozitáři nastavte tag `v0.2`.
