= filabel
:toc:
:note-caption: :information_source:
:warning-caption: :warning:

Tool for labeling PRs at GitHub by globs.


== Zadání úkolu 4

Vaším úkolem za 5 bodů je rozšířit testy k dosavadní úloze `filabel` pomocí
pytestu. Není nutné použít ``flexmock``, pokud to nepotřebujete. Využití ``betamax``u
je silně doporučeno.

Námi dodávané testy jsou tz. _akceptační_, skoro až _integrační_. Testují aplikaci
z venku, jako black box a navíc proti živému API. Rozšiřte testovací sadu o testy
_jednotkové_: tedy testy, které testují vaše vlastní metody, funkce, třídy apod.
Vaše testy již nesmí komunikovat s reálným GitHub API.

NOTE: Pokud jste předchozí úkoly nedělali a nebo neprochází testy,
můžete použít https://github.com/cvut/filabel/tree/v0.3[naše referenční řešení].

=== Podmínky:

* Musí fungovat `setup.py test` a to nejen z gitu, ale i při rozbalení archivu
  `sdist`.
* Všechny testovací závislosti se musí při uvedeném příkazu nainstalovat.
** Je nutné správně rozlišit testovací a runtime závislosti.
* Testy samotné musí fungovat offline a bez nutnosti mít přístupové údaje k API.
* Spuštění testů i znovu-nahrání kazet musí být zdokumentováno v `README`. Je nutné umožnit všem znovunahrát kazety (tedy i lidem, kteří nemají přístup k vašemu GitHub účtu). Pro (znovu)vytvoření situace pro nahrání kazet můžete (ale nemusíte) použít (či upravit) skript `setup.sh` z našich současných testů.
* Nahrané kazety musí být v gitu a být součástí balíčku (ale neinstalují se).
* Žádné nahrané kazety (ani jiné soubory) nesmí obsahovat citlivé údaje.
* Alespoň část testu by měla být parametrická.
* Musí být použit nativní způsob pytest testů (pytest umí spouštět i testy pro
  `unittest` apod.).
* Testuje se všechno ++*++.
* Testy musí běžet i na Travis CI (případně jiném veřejném CI).

+*+ Záměrně nestanovujeme podmínku na 100% pokrytí kódu testy.
Otestujte prostě kód tak, aby byly otestovány všechny podstatné součásti
včetně webové aplikace.

== Automatické testy

Námi dodané testy z minulých úloh jsou stále závazné, můžete (ale nemusíte) je
přibalit k vašim testům, ale musí být odděleny (například jiná složka).

Následuje text z minula, který stále platí:

WARNING: Testy **netestují splnění tohoto úkolu**,
Testují pouze to, že se nic nerozbilo.

NOTE: Před spuštěním testů předpokládejte, že je váš balíček nainstalován.
Toho můžete docílit například pomocí `pyhton setup.py develop`
nebo `pip install -e.`

Nově jsou dodány extra testy ve složce `test_module`, které simulují reálnou instalaci
vašeho balíčku `filabel` z naklonovaného repozitáře i z testovací PyPI. Navíc testují
i další náležitosti požadované v tomto zadání (sdist bez warningů, submoduly, závislosti,
klíčová slova a další metadata). Tyto testy vyžadují nastavené proměnné prostředí
`CTU_USERNAME` a `FILABEL_REPO` pro získání vaší verze filabelu (pipem a gitem). V rámci
testů spouští subprocesy a pokud se na vašem OS jmenují jinak nebo jsou v jiné cestě, než
standardně na Linuxu, budete muset upravit soubor `fixtures/test_config.cfg`. V případě
potřeby založte issue. Tyto testy nepracují s aktuálním kódem "kolem" nich, ale s tím, co
je dostupné přes PyPI (publikováno) a GitHub (napushováno). Testy spustíte pomocí:

[source,console]
$ python -m pytest -v test_module

Pro spuštění testů nainstalujte do virtuálního prostředí balík `pytest`.

Testy vyžadují určitý setup repozitářů. Pro jeho vytvoření použijte skript
`test_environment/setup.sh`. Je třeba nastavit proměnné prostředí
`GH_TOKEN` a `GH_USER`.
Token musí příslušet danému uživateli a mít scope `repo`.

Skript využívá program https://hub.github.com/[hub],
který si *nejprve zprovozněte*.

Testy jsou napsané tak, že pokud váš program funguje dle zadání,
dají se pouštět opakovaně. Pokud ale dle zadání nefunguje,
je třeba smazat všechny štítky.
Alternativně můžete testovací repozitáře smazat pomocí skriptu
`test_environment/delete.sh` (potřeba scope `delete_repo`) a vytvořit znovu.
Vytváření repozitářů a Pull Requestů může trvat jednotky minut.

Pro spuštění testů nastavte stejné proměnné prostředí (`GH_TOKEN` a `GH_USER`).

[source,console]
$ export GH_USER=anicka
$ export GH_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
$ python -m pytest -v test

Testy v souboru test_radioactive_waste.py trvají dlouho a mají potenciál
vyřadit vás na hodinu z přístupu ke GitHub API.
Když ladíte ostatní testy, doporučujeme je vypínat pomocí přepínače `-k`:

[source,console]
$ python -m pytest -v -k "not radioactive" test

Testy předpokládají, že se štítky mění podle běhu předchozích testů.
Nepouštějte tedy jednotlivé testy samostatně.

Testy si můžete zkopírovat k sobě do repozitáře, považujte je za Public Domain.
Nepřidejte ale do repozitáře omylem soubor `labels.real.cfg`,
který se v průběhu testů dočasně vytváří a obsahuje váš token.

NOTE: Testy proti živému API, navíc napsané tak,
že se jednotlivé testy navzájem ovlivňují, jsou ukázkou toho,
jak se to nemá dělat.
Pokud narazíte v testech na problém, nebo nevíte jak dál, zeptejte se.
K tomu, jak se to dělá pořádně, se v předmětu dostaneme později.

WARNING: Testy netestují barevnost výstupu. I neobarvený výstup projde testy.
Barevnost kontrolujte očima.

== Odevzdání úkolu

Úkol odevzdáváte tradičně s tagem `v0.4` a nahráním nové verze na (testovací
či pravou) PyPI. Použijte verzi 0.4 (případně 0.4.x v souladu s tagem).
